apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  # Flux Kustomizations
  - ./cnpg/ks.yaml
  - ./csi-driver-nfs/ks.yaml
  - ./intel-device-plugin/ks.yaml
  - ./node-feature-discovery/ks.yaml
