apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./configmap.yaml
  - ../../../base/network-system/metallb
  - ./ipaddresspool.yaml
  - ./l2advertisement.yaml
patches:
  - path: ./patch_helm-release.yaml
    target:
      kind: HelmRelease
      name: metallb-deployment
