apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:lFm1rLJ4y/ZoSLY=,iv:svqpXuvbJLhOmAk8pxMUMvMrlionzv+SX0MdkPbXAdM=,tag:qMg6eGyNOA0aX+bsIqeSCQ==,type:str]
sops:
  age:
    - recipient: age1kak7nac7pp9kel9cl43m93jdrdtzdqhw07dkc62hk0qvq37u05nqce5mf5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQnh4ejR5WVUzV2FqU2JB
        YUd2bVdPU2xZNXFXdVpOY1lqRW9PY3NUbXdzCkdlSFJERkNuWUdlZWd1anRpYU90
        ZkpJNDVEMVpOUERWUWNYNTl5OVIvL0kKLS0tIENwREhETG5PL2haWm8yZ08za0lx
        NUg0TWRmVTYwWnN6ZUJQNDZFQ0U5U3cKiVExxntcmN649ONojyk8bkmJJ3p8MjSU
        tJpjX8uAIm1sv8UhOh0FVGH9uBxRFZmsMdI5zCLD4n0w4jgZinf8oA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1sx0dh82apfxxdv9z0l77dmu00e9vz5rn3pfwwnxhwumdxmwy7gsshaxxlc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNDJwaENDVjA2WmdwTGJP
        RlNKTDhSLzNnUURqb3pUYzJKa3lUZTV1c2tzCmFKZ2pNeFJ2L0IwT1FDWDdXK0Jk
        QmM2TnNsOEsxMHVFdEQ5TUtwWExvSGsKLS0tIEZZK0VvZ2x1NUgvcEt6WTB3TUNM
        eXFLUzM5eFo1MEhLWjYrVUVDYTM3WDAK+OwxWrPSJQzrgZtoWKniHVotV6pBS9Pu
        zKC/yYZmVuZBaj5Q/X7piB6nmpzVse0EBoP0BLwoh2aIZ3vY7f6pXw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1ffeq7wngvj64rk8xv0syfrfqxpstst5wlld2dxqwr52wr3z9hv5qhyuwsd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NTJheWZkYVNHUzFML1Fr
        aW5RRlE5R2VOQWhCYnV0R2hjNjZvNzV5RERjCmFtYlgveXppOXVsalZmU2xiQVN2
        OW03cGtFRmg1eDVrWnJOa1NJdU9pQjgKLS0tIHpydGJ5dGxoUEZ6S0RPZXgrQmlu
        ZE0vNG81d1BmcEp0RWs1VWlxRnBwcHMKmj+BkU9CvdRHCT2Tx0NvfqGmrjYmTSGW
        iFSXYbkpyV+a9rUhlqWddkMbN98GlVPY30vw43ChWGn34xJ4YRAA/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-10T14:36:33Z"
  mac: ENC[AES256_GCM,data:SskPTIwP9Cutkeu1eoJlw7E4bMb+Tiq64OkQPVlxGtKE+ea16Q4W5VO2dvnFZ1fEPlqaKRVDxudYWbAwu3VTpuXcfN4YdR5OGKRk+Y5ImSrfUIp2pT+euZ2nhiljgRd8J3XlwAqITScRSocozrsxaX9t8UsoQY2dpDS2i4gj5e8=,iv:q0nP9HJgZQvTVxTkymnInZh2LANi/5PXsCU7G94fosE=,tag:C7wKkqU7le9D+8b0TaZEAg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
